/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Control.LembreteControl;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Kagi
 */
public class CadastroLembrete extends javax.swing.JFrame {

    private final LembreteControl lembreteControl;
    /**
     * Creates new form CadastroLembrete
     */
    public CadastroLembrete() {
        lembreteControl = new LembreteControl();
        initComponents();
    }

    public LembreteControl getLembreteControl()
    {
        return lembreteControl;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        LembreteTexto = new javax.swing.JTextArea();
        LembreteData = new com.toedter.calendar.JDateChooser();
        btnLembreteEscolher = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LembreteMarcaData = new javax.swing.JTextArea();
        btnLembreteSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        LembreteTexto.setColumns(20);
        LembreteTexto.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${lembreteControl.lembreteDigitado.anotacoes}"), LembreteTexto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(LembreteTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 90, 243, 330);
        getContentPane().add(LembreteData);
        LembreteData.setBounds(73, 86, 240, 30);

        btnLembreteEscolher.setText("Escolher");
        btnLembreteEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLembreteEscolherActionPerformed(evt);
            }
        });
        getContentPane().add(btnLembreteEscolher);
        btnLembreteEscolher.setBounds(130, 120, 100, 23);

        LembreteMarcaData.setColumns(20);
        LembreteMarcaData.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${lembreteControl.lembreteDigitado.data}"), LembreteMarcaData, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(LembreteMarcaData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 176, 240, 80);

        btnLembreteSalvar.setText("Salvar");
        btnLembreteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLembreteSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLembreteSalvar);
        btnLembreteSalvar.setBounds(390, 433, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela-Agenda---New-Dory-25-11-2015.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 500);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(706, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLembreteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLembreteSalvarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,
                "Deseja realmente salvar o Evento?",
                "Salvar Evento",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION);
                lembreteControl.salvar();
                JOptionPane.showMessageDialog(this,
                        "Evento foi salvo com sucesso",
                        "Novo Evento cadastrado",
                        
                        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLembreteSalvarActionPerformed

    private void btnLembreteEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLembreteEscolherActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        String dataFormatada = simpleDateFormat.format(this.LembreteData.getDate());
        
        this.LembreteMarcaData.append(dataFormatada + "\n");
    }//GEN-LAST:event_btnLembreteEscolherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLembrete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser LembreteData;
    private javax.swing.JTextArea LembreteMarcaData;
    private javax.swing.JTextArea LembreteTexto;
    private javax.swing.JButton btnLembreteEscolher;
    private javax.swing.JButton btnLembreteSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
