/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Control.UsuarioControl;
import gui.FaceDetection;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.highgui.VideoCapture;
import org.opencv.objdetect.CascadeClassifier;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;

/**
 *
 * @author Kagi
 */
public class CadastroUsuario extends javax.swing.JFrame {
    
private final UsuarioControl usuarioControl;

    int count = 0;
    VideoCapture webSource = null;
    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();
    CascadeClassifier faceDetector = new CascadeClassifier(FaceDetection.class.getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));
    MatOfRect faceDetections = new MatOfRect();

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        usuarioControl = new UsuarioControl();
        initComponents();
    }

    public UsuarioControl getUsuarioControl()
    {
        return usuarioControl;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btnCadastroNome = new javax.swing.JTextField();
        btnCadastroApelido = new javax.swing.JTextField();
        btnCadastroNascimento = new javax.swing.JTextField();
        btnCadastroEmail = new javax.swing.JTextField();
        btnNomeUsuario = new javax.swing.JTextField();
        btnCadastroSenha = new javax.swing.JPasswordField();
        btnCadastroPergunta = new javax.swing.JTextField();
        btnCadastroResposta = new javax.swing.JTextField();
        btnCadastroFacial = new javax.swing.JButton();
        btnCadastroSalvar = new javax.swing.JButton();
        LabelCadastroNome = new javax.swing.JLabel();
        LabelCadastroApelido = new javax.swing.JLabel();
        LabelCadastroEmail = new javax.swing.JLabel();
        LabelCadastroUsuario = new javax.swing.JLabel();
        LabelCadastroSenha = new javax.swing.JLabel();
        LabelCadastroResposta = new javax.swing.JLabel();
        LabelCadastroPergunta = new javax.swing.JLabel();
        LabelCadastroNascimento = new javax.swing.JLabel();
        FundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.nome}"), btnCadastroNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroNome);
        btnCadastroNome.setBounds(80, 180, 490, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.apelido}"), btnCadastroApelido, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroApelido);
        btnCadastroApelido.setBounds(80, 230, 140, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.nascimento}"), btnCadastroNascimento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnCadastroNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroNascimento);
        btnCadastroNascimento.setBounds(230, 230, 130, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.email}"), btnCadastroEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroEmail);
        btnCadastroEmail.setBounds(370, 230, 200, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.nomeUsuario}"), btnNomeUsuario, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnNomeUsuario);
        btnNomeUsuario.setBounds(80, 360, 250, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.senha}"), btnCadastroSenha, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroSenha);
        btnCadastroSenha.setBounds(340, 360, 230, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.pergunta}"), btnCadastroPergunta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroPergunta);
        btnCadastroPergunta.setBounds(80, 420, 490, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioControl.usuarioDigitado.resposta}"), btnCadastroResposta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(btnCadastroResposta);
        btnCadastroResposta.setBounds(80, 480, 490, 30);

        btnCadastroFacial.setText("Reconhecimento Facial");
        btnCadastroFacial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFacialActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroFacial);
        btnCadastroFacial.setBounds(260, 580, 170, 30);

        btnCadastroSalvar.setText("Salvar");
        btnCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroSalvar);
        btnCadastroSalvar.setBounds(260, 530, 150, 30);

        LabelCadastroNome.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroNome.setText("Nome");
        getContentPane().add(LabelCadastroNome);
        LabelCadastroNome.setBounds(80, 150, 50, 14);

        LabelCadastroApelido.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroApelido.setText("Apelido");
        getContentPane().add(LabelCadastroApelido);
        LabelCadastroApelido.setBounds(80, 210, 50, 14);

        LabelCadastroEmail.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroEmail.setText("E-mail");
        getContentPane().add(LabelCadastroEmail);
        LabelCadastroEmail.setBounds(390, 210, 28, 14);

        LabelCadastroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroUsuario.setText("Usuario");
        getContentPane().add(LabelCadastroUsuario);
        LabelCadastroUsuario.setBounds(80, 330, 60, 14);

        LabelCadastroSenha.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroSenha.setText("Senha");
        getContentPane().add(LabelCadastroSenha);
        LabelCadastroSenha.setBounds(350, 340, 30, 14);

        LabelCadastroResposta.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroResposta.setText("Resposta");
        getContentPane().add(LabelCadastroResposta);
        LabelCadastroResposta.setBounds(80, 460, 50, 14);

        LabelCadastroPergunta.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroPergunta.setText("Pergunta");
        getContentPane().add(LabelCadastroPergunta);
        LabelCadastroPergunta.setBounds(80, 400, 60, 14);

        LabelCadastroNascimento.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroNascimento.setText("Data de Nascimento");
        getContentPane().add(LabelCadastroNascimento);
        LabelCadastroNascimento.setBounds(230, 210, 120, 20);

        FundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/13942-NPBACT.png"))); // NOI18N
        getContentPane().add(FundoCadastro);
        FundoCadastro.setBounds(0, -30, 720, 860);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(734, 872));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNomeUsuarioActionPerformed

    private void btnCadastroNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroNascimentoActionPerformed

    private void btnCadastroFacialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFacialActionPerformed
        // TODO add your handling code here:
        FaceDetection tela01 = new FaceDetection();
        tela01.setVisible(true);
        
       
    }//GEN-LAST:event_btnCadastroFacialActionPerformed

    private void btnCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroSalvarActionPerformed
        // TODO add your handling code here:
        usuarioControl.salvar();
    }//GEN-LAST:event_btnCadastroSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoCadastro;
    private javax.swing.JLabel LabelCadastroApelido;
    private javax.swing.JLabel LabelCadastroEmail;
    private javax.swing.JLabel LabelCadastroNascimento;
    private javax.swing.JLabel LabelCadastroNome;
    private javax.swing.JLabel LabelCadastroPergunta;
    private javax.swing.JLabel LabelCadastroResposta;
    private javax.swing.JLabel LabelCadastroSenha;
    private javax.swing.JLabel LabelCadastroUsuario;
    private javax.swing.JTextField btnCadastroApelido;
    private javax.swing.JTextField btnCadastroEmail;
    private javax.swing.JButton btnCadastroFacial;
    private javax.swing.JTextField btnCadastroNascimento;
    private javax.swing.JTextField btnCadastroNome;
    private javax.swing.JTextField btnCadastroPergunta;
    private javax.swing.JTextField btnCadastroResposta;
    private javax.swing.JButton btnCadastroSalvar;
    private javax.swing.JPasswordField btnCadastroSenha;
    private javax.swing.JTextField btnNomeUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
