/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Control.ContatoControl;
import Control.GrupoControl;
import java.awt.Rectangle;
import javax.swing.JOptionPane;

/**
 *
 * @author Kagi
 */
public class Contato extends javax.swing.JFrame {

    private final ContatoControl contatoControl;
    private final GrupoControl grupoControl;
    
    /**
     * Creates new form CadastroContato
     */
    public Contato() {
        
         contatoControl = new ContatoControl();
         grupoControl = new GrupoControl();
        
        initComponents();
    }
    
    public ContatoControl getContatoControl()
    {
        return contatoControl;
    }
    
    public GrupoControl getGrupoControl()
    {
        return grupoControl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AgendaDoryPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AgendaDoryPU").createEntityManager();
        contatoQuery = java.beans.Beans.isDesignTime() ? null : AgendaDoryPUEntityManager.createQuery("SELECT c FROM Contato c");
        contatoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contatoQuery.getResultList();
        ctNome = new javax.swing.JTextField();
        ctApelido = new javax.swing.JTextField();
        ctTelefone = new javax.swing.JTextField();
        ctRua = new javax.swing.JTextField();
        ctBairro = new javax.swing.JTextField();
        ctMunicipio = new javax.swing.JTextField();
        ctEstado = new javax.swing.JTextField();
        ctNumero = new javax.swing.JTextField();
        ctEmail = new javax.swing.JTextField();
        ctCelular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMostrarContatos = new javax.swing.JTable();
        btnContatoSalvar = new javax.swing.JButton();
        btnContatoExcluir = new javax.swing.JButton();
        btnContatoNovo = new javax.swing.JButton();
        ctPesquisar = new javax.swing.JTextField();
        btnPesquisarCadastroContato = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        LabeldeNome = new javax.swing.JLabel();
        fundoContato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.nome}"), ctNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        ctNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNomeActionPerformed(evt);
            }
        });
        getContentPane().add(ctNome);
        ctNome.setBounds(700, 310, 530, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.apelido}"), ctApelido, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctApelido);
        ctApelido.setBounds(700, 370, 330, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.telefone}"), ctTelefone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctTelefone);
        ctTelefone.setBounds(700, 420, 170, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.rua}"), ctRua, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctRua);
        ctRua.setBounds(700, 500, 420, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.bairro}"), ctBairro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctBairro);
        ctBairro.setBounds(700, 550, 200, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.cidade}"), ctMunicipio, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctMunicipio);
        ctMunicipio.setBounds(910, 550, 210, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.estado}"), ctEstado, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctEstado);
        ctEstado.setBounds(1130, 550, 100, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.numero}"), ctNumero, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctNumero);
        ctNumero.setBounds(1130, 500, 100, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.email}"), ctEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctEmail);
        ctEmail.setBounds(1050, 420, 180, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.celular}"), ctCelular, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(ctCelular);
        ctCelular.setBounds(880, 420, 160, 30);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoTabela}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaMostrarContatos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${apelido}"));
        columnBinding.setColumnName("apelido");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celular}"));
        columnBinding.setColumnName("celular");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rua}"));
        columnBinding.setColumnName("Rua");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numero}"));
        columnBinding.setColumnName("Numero");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bairro}"));
        columnBinding.setColumnName("Bairro");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidade}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoSelecionado}"), tabelaMostrarContatos, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tabelaMostrarContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMostrarContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMostrarContatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 530, 530);

        btnContatoSalvar.setText("Salvar");
        btnContatoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContatoSalvar);
        btnContatoSalvar.setBounds(920, 240, 100, 30);

        btnContatoExcluir.setText("Excluir");
        btnContatoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnContatoExcluir);
        btnContatoExcluir.setBounds(1040, 240, 100, 30);

        btnContatoNovo.setText("Novo");
        btnContatoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnContatoNovo);
        btnContatoNovo.setBounds(780, 240, 120, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${contatoControl.contatoDigitado.nome}"), ctPesquisar, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        ctPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(ctPesquisar);
        ctPesquisar.setBounds(160, 80, 440, 30);

        btnPesquisarCadastroContato.setContentAreaFilled(false);
        btnPesquisarCadastroContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCadastroContatoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarCadastroContato);
        btnPesquisarCadastroContato.setBounds(80, 80, 60, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familia", "Amigos", "Escola", "Trabalho" }));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${grupoControl.grupoDigitado.nome}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${grupoControl.grupoDigitado.nome}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1050, 370, 180, 30);

        LabeldeNome.setText("Nome");
        getContentPane().add(LabeldeNome);
        LabeldeNome.setBounds(700, 290, 27, 14);

        fundoContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/contacts.png"))); // NOI18N
        getContentPane().add(fundoContato);
        fundoContato.setBounds(0, 0, 1319, 720);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1334, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContatoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoSalvarActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this,
                "Deseja realmente salvar o contato?",
                "Salvar Contato",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION);
                contatoControl.salvar();
                grupoControl.salvar();
                JOptionPane.showMessageDialog(this,
                        "Contato foi salvo com sucesso",
                        "Novo contato cadastrado",
                        
                        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnContatoSalvarActionPerformed

    private void tabelaMostrarContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMostrarContatosMouseClicked
        // TODO add your handling code here:
        int linha_selecionada = tabelaMostrarContatos.getSelectedRow();
        int coluna_selecionada = tabelaMostrarContatos.getSelectedColumn();
        Rectangle cedula = tabelaMostrarContatos.getCellRect(linha_selecionada, coluna_selecionada, false);
        
        ctNome.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,0));
        ctApelido.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,1));
        ctTelefone.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,2));
        ctCelular.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,3));
        ctEmail.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,4));
        ctRua.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,5));
        ctNumero.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,6));
        ctBairro.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,7));
        ctMunicipio.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,8));
        ctEstado.setText((String) tabelaMostrarContatos.getValueAt(linha_selecionada,9));
    }//GEN-LAST:event_tabelaMostrarContatosMouseClicked

    private void btnContatoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoExcluirActionPerformed
        // TODO add your handling code here:
        contatoControl.excluir();
        grupoControl.excluir();
    }//GEN-LAST:event_btnContatoExcluirActionPerformed

    private void btnContatoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoNovoActionPerformed
        // TODO add your handling code here:
        contatoControl.novo();
        grupoControl.novo();
    }//GEN-LAST:event_btnContatoNovoActionPerformed

    private void btnPesquisarCadastroContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCadastroContatoActionPerformed
        // TODO add your handling code here:
        contatoControl.pesquisar();
        grupoControl.pesquisar();
    }//GEN-LAST:event_btnPesquisarCadastroContatoActionPerformed

    private void ctNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNomeActionPerformed

    private void ctPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AgendaDoryPUEntityManager;
    private javax.swing.JLabel LabeldeNome;
    private javax.swing.JButton btnContatoExcluir;
    private javax.swing.JButton btnContatoNovo;
    private javax.swing.JButton btnContatoSalvar;
    private javax.swing.JButton btnPesquisarCadastroContato;
    private java.util.List<Model.Contato> contatoList;
    private javax.persistence.Query contatoQuery;
    private javax.swing.JTextField ctApelido;
    private javax.swing.JTextField ctBairro;
    private javax.swing.JTextField ctCelular;
    private javax.swing.JTextField ctEmail;
    private javax.swing.JTextField ctEstado;
    private javax.swing.JTextField ctMunicipio;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctNumero;
    private javax.swing.JTextField ctPesquisar;
    private javax.swing.JTextField ctRua;
    private javax.swing.JTextField ctTelefone;
    private javax.swing.JLabel fundoContato;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMostrarContatos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
