/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Control.EventosControl;

/**
 *
 * @author Kagi
 */
public class Evento extends javax.swing.JFrame {
    
    private final EventosControl eventoControl;

    /**
     * Creates new form Evento
     */
    public Evento() {
        eventoControl = new EventosControl();
        initComponents();
    }

    
    public EventosControl getEventoControl()
    {
        return eventoControl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AgendaDoryPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AgendaDoryPU").createEntityManager();
        eventosQuery = java.beans.Beans.isDesignTime() ? null : AgendaDoryPUEntityManager.createQuery("SELECT e FROM Eventos e");
        eventosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : eventosQuery.getResultList();
        eventosQuery1 = java.beans.Beans.isDesignTime() ? null : AgendaDoryPUEntityManager.createQuery("SELECT e FROM Eventos e");
        eventosList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : eventosQuery1.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaeventos = new javax.swing.JTable();
        fundoEventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, eventosList1, tabelaeventos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horario}"));
        columnBinding.setColumnName("Horario");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${eventoControl.contatoTabela}"), tabelaeventos, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tabelaeventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaeventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaeventos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 680, 580);

        fundoEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lembrete.png"))); // NOI18N
        getContentPane().add(fundoEventos);
        fundoEventos.setBounds(0, 0, 800, 800);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(816, 836));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaeventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaeventosMouseClicked
        // TODO add your handling code here:,                                      
        
    }//GEN-LAST:event_tabelaeventosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AgendaDoryPUEntityManager;
    private java.util.List<Model.Eventos> eventosList;
    private java.util.List<Model.Eventos> eventosList1;
    private javax.persistence.Query eventosQuery;
    private javax.persistence.Query eventosQuery1;
    private javax.swing.JLabel fundoEventos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaeventos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
