/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Kagi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicioNoticias = new javax.swing.JButton();
        btnInicioEventos = new javax.swing.JButton();
        btnInicioLembretes = new javax.swing.JButton();
        btnInicioContatos = new javax.swing.JButton();
        btnInicioFeedback = new javax.swing.JButton();
        btnInicioLinkedin = new javax.swing.JButton();
        btnInicioFacebook = new javax.swing.JButton();
        btnInicioTwitter = new javax.swing.JButton();
        btnInicioConfiguracao = new javax.swing.JButton();
        labeldahora = new javax.swing.JLabel();
        labeldadata = new javax.swing.JLabel();
        btnPesquisarBingInicio = new javax.swing.JButton();
        fundoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnInicioNoticias.setToolTipText("Botão Noticias");
        btnInicioNoticias.setContentAreaFilled(false);
        btnInicioNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioNoticiasActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioNoticias);
        btnInicioNoticias.setBounds(270, 150, 140, 170);

        btnInicioEventos.setToolTipText("Botão Evento");
        btnInicioEventos.setContentAreaFilled(false);
        btnInicioEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioEventosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioEventos);
        btnInicioEventos.setBounds(390, 320, 130, 120);

        btnInicioLembretes.setToolTipText("Botão Lembrete");
        btnInicioLembretes.setContentAreaFilled(false);
        btnInicioLembretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLembretesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioLembretes);
        btnInicioLembretes.setBounds(430, 460, 100, 150);

        btnInicioContatos.setToolTipText("Botão Contatos");
        btnInicioContatos.setContentAreaFilled(false);
        btnInicioContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioContatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioContatos);
        btnInicioContatos.setBounds(80, 300, 110, 220);

        btnInicioFeedback.setToolTipText("Botão feedback");
        btnInicioFeedback.setContentAreaFilled(false);
        btnInicioFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioFeedback);
        btnInicioFeedback.setBounds(0, 550, 170, 130);

        btnInicioLinkedin.setToolTipText("Botão Linkedin");
        btnInicioLinkedin.setContentAreaFilled(false);
        btnInicioLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinkedinActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioLinkedin);
        btnInicioLinkedin.setBounds(260, 480, 90, 80);

        btnInicioFacebook.setToolTipText("Botão facebook");
        btnInicioFacebook.setContentAreaFilled(false);
        btnInicioFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioFacebookActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioFacebook);
        btnInicioFacebook.setBounds(190, 530, 60, 90);

        btnInicioTwitter.setToolTipText("Botão Twitter");
        btnInicioTwitter.setContentAreaFilled(false);
        btnInicioTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioTwitterActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioTwitter);
        btnInicioTwitter.setBounds(260, 560, 90, 60);

        btnInicioConfiguracao.setToolTipText("Botão configuração");
        btnInicioConfiguracao.setContentAreaFilled(false);
        btnInicioConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioConfiguracaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioConfiguracao);
        btnInicioConfiguracao.setBounds(300, 620, 120, 100);

        labeldahora.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        labeldahora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labeldahora);
        labeldahora.setBounds(0, 160, 100, 40);

        labeldadata.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        labeldadata.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labeldadata);
        labeldadata.setBounds(0, 200, 100, 40);

        btnPesquisarBingInicio.setContentAreaFilled(false);
        btnPesquisarBingInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarBingInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarBingInicio);
        btnPesquisarBingInicio.setBounds(10, 50, 210, 120);

        fundoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tela principal.png"))); // NOI18N
        getContentPane().add(fundoInicio);
        fundoInicio.setBounds(0, 0, 1310, 740);

        setSize(new java.awt.Dimension(1296, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioContatosActionPerformed
        // TODO add your handling code here:
        Contato tela01 = new Contato();
        tela01.setVisible(true);
    }//GEN-LAST:event_btnInicioContatosActionPerformed

    private void btnInicioNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioNoticiasActionPerformed
        // TODO add your handling code here:
        TelaNoticias tela03 = new TelaNoticias();
        tela03.setVisible(true);
        
    }//GEN-LAST:event_btnInicioNoticiasActionPerformed

    private void btnInicioEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioEventosActionPerformed
        // TODO add your handling code here:
        TelaEventos tela04 = new TelaEventos();
        tela04.setVisible(true);
    }//GEN-LAST:event_btnInicioEventosActionPerformed

    private void btnInicioLembretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLembretesActionPerformed
        // TODO add your handling code here:
        TelaLembretes tela05 = new TelaLembretes();
        tela05.setVisible(true);
    }//GEN-LAST:event_btnInicioLembretesActionPerformed

    private void btnInicioFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioFeedbackActionPerformed
        // TODO add your handling code here:
        Feedback navegador01 = new Feedback();
        navegador01.setVisible(true);
    }//GEN-LAST:event_btnInicioFeedbackActionPerformed

    private void btnInicioFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioFacebookActionPerformed
        // TODO add your handling code here:
        Facebook navegador02 = new Facebook();
        navegador02.setVisible(true);
        navegador02.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInicioFacebookActionPerformed

    private void btnInicioLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinkedinActionPerformed
        // TODO add your handling code here:
        Linkedin navegador03 = new Linkedin();
        navegador03.setVisible(true);
    }//GEN-LAST:event_btnInicioLinkedinActionPerformed

    private void btnInicioTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioTwitterActionPerformed
        // TODO add your handling code here:
        Twitter navegador04 = new Twitter();
        navegador04.setVisible(true);
    }//GEN-LAST:event_btnInicioTwitterActionPerformed

    private void btnInicioConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioConfiguracaoActionPerformed
        // TODO add your handling code here:
         Configuração configuracao = new Configuração();
        configuracao.setVisible(true);
    }//GEN-LAST:event_btnInicioConfiguracaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //DATA
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        labeldadata.setText(formato.format(dataSistema));
        
        // Hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisarBingInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarBingInicioActionPerformed
        // TODO add your handling code here:
        BING pesquisar = new BING();
        pesquisar.setVisible(true);
    }//GEN-LAST:event_btnPesquisarBingInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioConfiguracao;
    private javax.swing.JButton btnInicioContatos;
    private javax.swing.JButton btnInicioEventos;
    private javax.swing.JButton btnInicioFacebook;
    private javax.swing.JButton btnInicioFeedback;
    private javax.swing.JButton btnInicioLembretes;
    private javax.swing.JButton btnInicioLinkedin;
    private javax.swing.JButton btnInicioNoticias;
    private javax.swing.JButton btnInicioTwitter;
    private javax.swing.JButton btnPesquisarBingInicio;
    private javax.swing.JLabel fundoInicio;
    private javax.swing.JLabel labeldadata;
    private javax.swing.JLabel labeldahora;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            Calendar now = Calendar.getInstance();
            labeldahora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}
