/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

/**
 *
 * @author Kagi
 */
public class TelaEventos extends javax.swing.JFrame {

    /**
     * Creates new form TelaEventos
     */
    public TelaEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaCadastroEventos = new javax.swing.JButton();
        btnTelaVisualizarEventos = new javax.swing.JButton();
        fundotelaeventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnTelaCadastroEventos.setToolTipText("Botão cadastrar evento");
        btnTelaCadastroEventos.setContentAreaFilled(false);
        btnTelaCadastroEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroEventosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaCadastroEventos);
        btnTelaCadastroEventos.setBounds(320, 150, 100, 80);

        btnTelaVisualizarEventos.setToolTipText("botão visualizar eventos");
        btnTelaVisualizarEventos.setBorderPainted(false);
        btnTelaVisualizarEventos.setContentAreaFilled(false);
        btnTelaVisualizarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaVisualizarEventosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaVisualizarEventos);
        btnTelaVisualizarEventos.setBounds(420, 260, 90, 90);

        fundotelaeventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaeventos.png"))); // NOI18N
        getContentPane().add(fundotelaeventos);
        fundotelaeventos.setBounds(0, 0, 800, 660);

        setSize(new java.awt.Dimension(814, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaCadastroEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroEventosActionPerformed
        // TODO add your handling code here:
        CadastroEvento tela01 =new CadastroEvento();
        tela01.setVisible(true);
    }//GEN-LAST:event_btnTelaCadastroEventosActionPerformed

    private void btnTelaVisualizarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaVisualizarEventosActionPerformed
        // TODO add your handling code here:
        Evento tela02 = new Evento();
        tela02.setVisible(true);
    }//GEN-LAST:event_btnTelaVisualizarEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaCadastroEventos;
    private javax.swing.JButton btnTelaVisualizarEventos;
    private javax.swing.JLabel fundotelaeventos;
    // End of variables declaration//GEN-END:variables
}
