/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

/**
 *
 * @author Kagi
 */
public class TelaLembretes extends javax.swing.JFrame {

    /**
     * Creates new form TekaLembretes
     */
    public TelaLembretes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaCadastroLembrete = new javax.swing.JButton();
        btnTelaVisualizarLembrete = new javax.swing.JButton();
        fundotelalembretes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnTelaCadastroLembrete.setToolTipText("Botão Cadastrar lembrete");
        btnTelaCadastroLembrete.setBorderPainted(false);
        btnTelaCadastroLembrete.setContentAreaFilled(false);
        btnTelaCadastroLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroLembreteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaCadastroLembrete);
        btnTelaCadastroLembrete.setBounds(260, 320, 130, 150);

        btnTelaVisualizarLembrete.setToolTipText("Botão Visualizar lembrete");
        btnTelaVisualizarLembrete.setContentAreaFilled(false);
        btnTelaVisualizarLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaVisualizarLembreteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaVisualizarLembrete);
        btnTelaVisualizarLembrete.setBounds(430, 480, 140, 130);

        fundotelalembretes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaLembrete.png"))); // NOI18N
        getContentPane().add(fundotelalembretes);
        fundotelalembretes.setBounds(0, 0, 800, 780);

        setSize(new java.awt.Dimension(814, 819));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaCadastroLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroLembreteActionPerformed
        // TODO add your handling code here:
        CadastroLembrete tela01 = new CadastroLembrete();
        tela01.setVisible(true);
    }//GEN-LAST:event_btnTelaCadastroLembreteActionPerformed

    private void btnTelaVisualizarLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaVisualizarLembreteActionPerformed
        // TODO add your handling code here:
        Lembrete tela02 = new Lembrete();
        tela02.setVisible(true);
    }//GEN-LAST:event_btnTelaVisualizarLembreteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLembretes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaCadastroLembrete;
    private javax.swing.JButton btnTelaVisualizarLembrete;
    private javax.swing.JLabel fundotelalembretes;
    // End of variables declaration//GEN-END:variables
}
