/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

/**
 *
 * @author Kagi
 */
public class TelaNoticias extends javax.swing.JFrame {

    /**
     * Creates new form TelaNoticias
     */
    public TelaNoticias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNoticiasBBC = new javax.swing.JButton();
        btnNoticiasEstadao = new javax.swing.JButton();
        btnNoticiasFolha = new javax.swing.JButton();
        btnNoticiasReuters = new javax.swing.JButton();
        btnNoticiasInvesting = new javax.swing.JButton();
        btnNoticiasOlharDigital = new javax.swing.JButton();
        btnNoticiasFamososGlobo = new javax.swing.JButton();
        btnNoticiasGloboEsporte = new javax.swing.JButton();
        btnNoticiasEsporteInterativo = new javax.swing.JButton();
        fundonoticias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnNoticiasBBC.setContentAreaFilled(false);
        btnNoticiasBBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasBBCActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasBBC);
        btnNoticiasBBC.setBounds(470, 160, 130, 90);

        btnNoticiasEstadao.setContentAreaFilled(false);
        btnNoticiasEstadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasEstadaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasEstadao);
        btnNoticiasEstadao.setBounds(610, 160, 120, 90);

        btnNoticiasFolha.setContentAreaFilled(false);
        btnNoticiasFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasFolhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasFolha);
        btnNoticiasFolha.setBounds(740, 160, 120, 90);

        btnNoticiasReuters.setContentAreaFilled(false);
        btnNoticiasReuters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasReutersActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasReuters);
        btnNoticiasReuters.setBounds(480, 250, 120, 80);

        btnNoticiasInvesting.setContentAreaFilled(false);
        btnNoticiasInvesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasInvestingActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasInvesting);
        btnNoticiasInvesting.setBounds(610, 250, 120, 80);

        btnNoticiasOlharDigital.setToolTipText("");
        btnNoticiasOlharDigital.setContentAreaFilled(false);
        btnNoticiasOlharDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasOlharDigitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasOlharDigital);
        btnNoticiasOlharDigital.setBounds(740, 250, 120, 80);

        btnNoticiasFamososGlobo.setContentAreaFilled(false);
        btnNoticiasFamososGlobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasFamososGloboActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasFamososGlobo);
        btnNoticiasFamososGlobo.setBounds(480, 340, 120, 50);

        btnNoticiasGloboEsporte.setContentAreaFilled(false);
        btnNoticiasGloboEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasGloboEsporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasGloboEsporte);
        btnNoticiasGloboEsporte.setBounds(610, 340, 110, 50);

        btnNoticiasEsporteInterativo.setContentAreaFilled(false);
        btnNoticiasEsporteInterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiasEsporteInterativoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoticiasEsporteInterativo);
        btnNoticiasEsporteInterativo.setBounds(730, 340, 130, 50);

        fundonoticias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaNoticias.png"))); // NOI18N
        getContentPane().add(fundonoticias);
        fundonoticias.setBounds(0, 0, 1210, 690);

        setSize(new java.awt.Dimension(1214, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoticiasBBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasBBCActionPerformed
        // TODO add your handling code here:
        BBC noticias02 = new BBC();
        noticias02.setVisible(true);
    }//GEN-LAST:event_btnNoticiasBBCActionPerformed

    private void btnNoticiasEstadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasEstadaoActionPerformed
        // TODO add your handling code here:
        Estadao noticias03 = new Estadao();
        noticias03.setVisible(true);
    }//GEN-LAST:event_btnNoticiasEstadaoActionPerformed

    private void btnNoticiasFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasFolhaActionPerformed
        // TODO add your handling code here:
        Folha  noticias05 = new Folha ();
        noticias05.setVisible(true);
    }//GEN-LAST:event_btnNoticiasFolhaActionPerformed

    private void btnNoticiasReutersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasReutersActionPerformed
        // TODO add your handling code here:
        Reuters  noticias09 = new Reuters ();
        noticias09.setVisible(true);
    }//GEN-LAST:event_btnNoticiasReutersActionPerformed

    private void btnNoticiasInvestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasInvestingActionPerformed
        // TODO add your handling code here:
        Investing  noticias08 = new Investing ();
        noticias08.setVisible(true);
    }//GEN-LAST:event_btnNoticiasInvestingActionPerformed

    private void btnNoticiasOlharDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasOlharDigitalActionPerformed
        // TODO add your handling code here:
        OlharDigital noticias01 = new OlharDigital();
        noticias01.setVisible(true);
    }//GEN-LAST:event_btnNoticiasOlharDigitalActionPerformed

    private void btnNoticiasFamososGloboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasFamososGloboActionPerformed
        // TODO add your handling code here:
        Famosos  noticias06 = new Famosos ();
        noticias06.setVisible(true);
    }//GEN-LAST:event_btnNoticiasFamososGloboActionPerformed

    private void btnNoticiasGloboEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasGloboEsporteActionPerformed
        // TODO add your handling code here:
        GloboEsporte  noticias07 = new GloboEsporte ();
        noticias07.setVisible(true);
    }//GEN-LAST:event_btnNoticiasGloboEsporteActionPerformed

    private void btnNoticiasEsporteInterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiasEsporteInterativoActionPerformed
        // TODO add your handling code here:
        EsporteInterativo  noticias04 = new EsporteInterativo ();
        noticias04.setVisible(true);
    }//GEN-LAST:event_btnNoticiasEsporteInterativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNoticias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoticiasBBC;
    private javax.swing.JButton btnNoticiasEsporteInterativo;
    private javax.swing.JButton btnNoticiasEstadao;
    private javax.swing.JButton btnNoticiasFamososGlobo;
    private javax.swing.JButton btnNoticiasFolha;
    private javax.swing.JButton btnNoticiasGloboEsporte;
    private javax.swing.JButton btnNoticiasInvesting;
    private javax.swing.JButton btnNoticiasOlharDigital;
    private javax.swing.JButton btnNoticiasReuters;
    private javax.swing.JLabel fundonoticias;
    // End of variables declaration//GEN-END:variables
}
